class MockDataSeeder {
  static List<Map<String, dynamic>> getEgyptianProperties() {
    return [
      // ===== Cairo =====
      {
        'id': 'egy1',
        'title': 'شقة فاخرة على النيل - المعادي',
        'price': '15,000',
        'location': 'المعادي، القاهرة',
        'governorate': 'القاهرة',
        'lat': 29.9537,
        'lng': 31.2559,
        'image': 'assets/images/home1.jpg',
        'beds': '3',
        'baths': '2',
        'area': '200',
        'ownerId': 'owner@ejari.app',
        'type': 'شقق',
        'amenities': ['إطلالة نيلية', 'أمن 24/7', 'تكييف مركزي', 'موقف سيارات'],
        'furnished': true,
        'listingMode': 'rent',
        'status': 'approved',
        'isDemo': true,
        'phone': '01012345678',
        'supportedDurations': ['يوم', 'أسبوع', 'شهر', 'سنة'],
        'corporateEligible': true,
      },
      {
        'id': 'egy2',
        'title': 'فيلا مستقلة التجمع الخامس',
        'price': '45,000',
        'location': 'التجمع الخامس، القاهرة',
        'governorate': 'القاهرة',
        'lat': 30.0166,
        'lng': 31.4398,
        'image': 'assets/images/home2.jpg',
        'beds': '5',
        'baths': '4',
        'area': '450',
        'ownerId': 'owner@ejari.app',
        'type': 'فلل',
        'amenities': ['حمام سباحة', 'حديقة خاصة', 'تشطيب ألترا مودرن'],
        'furnished': true,
        'listingMode': 'rent',
        'status': 'approved',
        'isDemo': true,
        'phone': '01012345678',
        'supportedDurations': ['شهر', 'سنة'],
        'corporateEligible': true,
      },
      {
        'id': 'egy3',
        'title': 'استوديو مفروش - مدينة نصر',
        'price': '6,000',
        'location': 'مدينة نصر، القاهرة',
        'governorate': 'القاهرة',
        'lat': 30.0541,
        'lng': 31.3283,
        'image': 'assets/images/home7.jpg',
        'beds': '1',
        'baths': '1',
        'area': '65',
        'ownerId': 'owner@ejari.app',
        'type': 'استوديو',
        'amenities': ['مفروش بالكامل', 'واي فاي', 'بالقرب من سيتي ستارز'],
        'furnished': true,
        'listingMode': 'rent',
        'status': 'approved',
        'isDemo': true,
        'phone': '01012345678',
        'supportedDurations': ['يوم', 'أسبوع', 'شهر'],
        'corporateEligible': true,
      },
      {
        'id': 'egy8',
        'title': 'شقة للإيجار - مصر الجديدة',
        'price': '12,000',
        'location': 'مصر الجديدة، القاهرة',
        'governorate': 'القاهرة',
        'lat': 30.0872,
        'lng': 31.3308,
        'image': 'assets/images/home1.jpg',
        'beds': '2',
        'baths': '1',
        'area': '120',
        'ownerId': 'owner_8',
        'type': 'شقق',
        'amenities': ['مفروشة', 'أسانسير', 'قريبة من المترو'],
        'furnished': true,
        'listingMode': 'rent',
        'status': 'approved',
        'isDemo': true,
        'phone': '01012345678',
        'supportedDurations': ['شهر', 'سنة'],
        'corporateEligible': true,
      },
      {
        'id': 'egy9',
        'title': 'شقة يومية - وسط البلد',
        'price': '800',
        'location': 'وسط البلد، القاهرة',
        'governorate': 'القاهرة',
        'lat': 30.0444,
        'lng': 31.2357,
        'image': 'assets/images/home3.jpg',
        'beds': '1',
        'baths': '1',
        'area': '55',
        'ownerId': 'owner_9',
        'type': 'شقق',
        'amenities': ['إيجار يومي', 'مفروش', 'واي فاي'],
        'furnished': true,
        'listingMode': 'rent',
        'status': 'approved',
        'isDemo': true,
        'phone': '01012345678',
        'supportedDurations': ['يوم', 'أسبوع'],
        'corporateEligible': false,
      },
      // ===== Giza =====
      {
        'id': 'egy4',
        'title': 'شقة دوبلكس - الشيخ زايد',
        'price': '22,000',
        'location': 'الشيخ زايد، الجيزة',
        'governorate': 'الجيزة',
        'lat': 30.0345,
        'lng': 30.9850,
        'image': 'assets/images/home3.jpg',
        'beds': '4',
        'baths': '3',
        'area': '320',
        'ownerId': 'owner_4',
        'type': 'دوبلكس',
        'amenities': ['روف خاص', 'كمبوند مغلق', 'كلوب هاوس'],
        'furnished': false,
        'listingMode': 'rent',
        'status': 'approved',
        'isDemo': true,
        'phone': '01012345678',
        'supportedDurations': ['شهر', 'سنة'],
        'corporateEligible': true,
      },
      {
        'id': 'egy5',
        'title': 'شقة لقطة للبيع - المهندسين',
        'price': '3,500,000',
        'location': 'المهندسين، الجيزة',
        'governorate': 'الجيزة',
        'lat': 30.0520,
        'lng': 31.2017,
        'image': 'assets/images/home4.jpg',
        'beds': '3',
        'baths': '2',
        'area': '180',
        'ownerId': 'owner_5',
        'type': 'شقق',
        'amenities': ['مسجل شهر عقاري', 'موقع تجاري'],
        'furnished': false,
        'listingMode': 'for_sale',
        'status': 'approved',
        'isDemo': true,
        'phone': '01012345678',
        'supportedDurations': [],
        'corporateEligible': false,
      },
      {
        'id': 'egy10',
        'title': 'شقة للإيجار - ٦ أكتوبر',
        'price': '9,500',
        'location': '٦ أكتوبر، الجيزة',
        'governorate': 'الجيزة',
        'lat': 29.9285,
        'lng': 30.9188,
        'image': 'assets/images/home4.jpg',
        'beds': '2',
        'baths': '2',
        'area': '140',
        'ownerId': 'owner_10',
        'type': 'شقق',
        'amenities': ['كمبوند', 'موقف', 'أمن'],
        'furnished': true,
        'listingMode': 'rent',
        'status': 'approved',
        'isDemo': true,
        'phone': '01012345678',
        'supportedDurations': ['شهر', 'سنة'],
        'corporateEligible': true,
      },
      // ===== Alexandria =====
      {
        'id': 'egy6',
        'title': 'شقة بانوراما بحر - جليم',
        'price': '12,000',
        'location': 'جليم، الإسكندرية',
        'governorate': 'الإسكندرية',
        'lat': 31.2407,
        'lng': 29.9701,
        'image': 'assets/images/home5.jpg',
        'beds': '2',
        'baths': '2',
        'area': '150',
        'ownerId': 'owner_6',
        'type': 'شقق',
        'amenities': ['إطلالة مباشرة على البحر', 'مكيفة', 'أسانسير'],
        'furnished': true,
        'listingMode': 'rent',
        'status': 'approved',
        'isDemo': true,
        'phone': '01012345678',
        'supportedDurations': ['أسبوع', 'شهر', 'سنة'],
        'corporateEligible': true,
      },
      {
        'id': 'egy11',
        'title': 'شقة للإيجار - سموحة',
        'price': '10,500',
        'location': 'سموحة، الإسكندرية',
        'governorate': 'الإسكندرية',
        'lat': 31.2156,
        'lng': 29.9553,
        'image': 'assets/images/home5.jpg',
        'beds': '3',
        'baths': '2',
        'area': '165',
        'ownerId': 'owner_11',
        'type': 'شقق',
        'amenities': ['مفروشة', 'بالقرب من الكورنيش'],
        'furnished': true,
        'listingMode': 'rent',
        'status': 'approved',
        'isDemo': true,
        'phone': '01012345678',
        'supportedDurations': ['شهر', 'سنة'],
        'corporateEligible': true,
      },
      // ===== North Coast / Short-stay vacation (FB-style) =====
      {
        'id': 'egy7',
        'title': 'شاليه الساحل الشمالي — سيدي عبدالرحمن',
        'price': '12,000',
        'dailyPrice': '600',
        'location': 'سيدي عبدالرحمن، الساحل الشمالي',
        'governorate': 'مطروح',
        'region': 'الساحل الشمالي',
        'lat': 30.9320,
        'lng': 28.7180,
        'image': 'assets/images/home6.jpg',
        'beds': '3',
        'baths': '2',
        'area': '120',
        'ownerId': 'owner_7',
        'type': 'شاليهات',
        'amenities': [
          'قريب من البحر',
          'مكيف',
          'واي فاي',
          'مطبخ',
          'قرية سياحية',
          'تشطيب لوكس',
        ],
        'furnished': true,
        'listingMode': 'rent',
        'status': 'approved',
        'isDemo': true,
        'isFeatured': true,
        'shortStay': true,
        'phone': '01012345678',
        'supportedDurations': ['يوم', 'أسبوع', 'شهر'],
        'corporateEligible': false,
        'nearbyBeachMinutes': 5,
        'carAvailable': false,
        'familyFriendly': true,
        'independentHouse': false,
        'packageHalfWeek': 3500,
        'specialOffers': [
          {
            'title': 'باقة نصف أسبوع',
            'days': 7,
            'pricePerDay': 500,
            'label': 'نصف أسبوع',
          },
          {
            'title': 'عرض ٣ أيام',
            'days': 3,
            'pricePerDay': 550,
            'label': 'عرض ٣ أيام',
          },
        ],
      },
      {
        'id': 'vac_matrouh_1',
        'title': 'بيت مستقل فاخر للعائلات — مطروح قرب الفيروز',
        'price': '11,000',
        'dailyPrice': '550',
        'location': 'مرسى مطروح، قرب شاطئ الفيروز (٨ دقائق مشي)',
        'address': 'مطروح — منطقة الفيروز',
        'governorate': 'مطروح',
        'region': 'مطروح',
        'lat': 31.3525,
        'lng': 27.2373,
        'image': 'assets/images/home3.jpg',
        'beds': '4',
        'baths': '1',
        'area': '140',
        'ownerId': 'owner@ejari.app',
        'type': 'فلل',
        'amenities': [
          'قريب من البحر',
          'بيت مستقل',
          'مناسب للعائلات',
          'مطبخ',
          'مكيف',
          'واي فاي',
          'تشطيب لوكس',
          'سراير متعددة',
          '٢ غرف + صالون',
        ],
        'furnished': true,
        'listingMode': 'rent',
        'status': 'approved',
        'isDemo': true,
        'isFeatured': true,
        'shortStay': true,
        'phone': '01098765432',
        'supportedDurations': ['يوم', 'أسبوع', 'شهر'],
        'corporateEligible': false,
        'nearbyBeachMinutes': 8,
        'carAvailable': true,
        'familyFriendly': true,
        'independentHouse': true,
        'packageHalfWeek': 3200,
        'specialOffers': [
          {
            'title': 'عرض ٣ أيام',
            'days': 3,
            'pricePerDay': 550,
            'label': 'عرض ٣ أيام',
          },
          {
            'title': 'نصف أسبوع (٧ ليالي)',
            'days': 7,
            'pricePerDay': 457,
            'label': 'نصف أسبوع',
          },
        ],
      },
      {
        'id': 'vac_matrouh_2',
        'title': 'شقتين بسعر خاص — الساحل الشمالي',
        'price': '18,000',
        'dailyPrice': '900',
        'location': 'العلمين، الساحل الشمالي',
        'governorate': 'مطروح',
        'region': 'الساحل الشمالي',
        'lat': 30.8400,
        'lng': 28.9500,
        'image': 'assets/images/home2.jpg',
        'beds': '6',
        'baths': '3',
        'area': '220',
        'ownerId': 'owner_7',
        'type': 'شقق',
        'amenities': [
          'قريب من البحر',
          'مطبخ',
          'مكيف',
          'واي فاي',
          'مناسب للعائلات',
          'سراير متعددة',
          'تشطيب لوكس',
        ],
        'furnished': true,
        'listingMode': 'rent',
        'status': 'approved',
        'isDemo': true,
        'isFeatured': true,
        'shortStay': true,
        'multiUnitDeal': true,
        'phone': '01012345678',
        'supportedDurations': ['يوم', 'أسبوع', 'شهر'],
        'corporateEligible': false,
        'nearbyBeachMinutes': 10,
        'carAvailable': true,
        'familyFriendly': true,
        'independentHouse': false,
        'packageHalfWeek': 5500,
        'specialOffers': [
          {
            'title': 'شقتين بسعر خاص',
            'days': 7,
            'pricePerDay': 785,
            'label': 'شقتين بسعر خاص',
          },
          {
            'title': 'عرض ٣ أيام لعائلتين',
            'days': 3,
            'pricePerDay': 850,
            'label': 'عرض ٣ أيام',
          },
        ],
      },
      {
        'id': 'vac_alex_1',
        'title': 'شقة كورنيش الإسكندرية — إطلالة بحر',
        'price': '9,000',
        'dailyPrice': '450',
        'location': 'ستانلي، الإسكندرية',
        'governorate': 'الإسكندرية',
        'region': 'الإسكندرية',
        'lat': 31.2156,
        'lng': 29.9553,
        'image': 'assets/images/home1.jpg',
        'beds': '2',
        'baths': '1',
        'area': '95',
        'ownerId': 'owner_alex',
        'type': 'شقق',
        'amenities': [
          'قريب من البحر',
          'مكيف',
          'واي فاي',
          'مطبخ',
          'تشطيب لوكس',
        ],
        'furnished': true,
        'listingMode': 'rent',
        'status': 'approved',
        'isDemo': true,
        'shortStay': true,
        'phone': '01055556666',
        'supportedDurations': ['يوم', 'أسبوع', 'شهر'],
        'corporateEligible': false,
        'nearbyBeachMinutes': 3,
        'carAvailable': false,
        'familyFriendly': true,
        'independentHouse': false,
        'packageHalfWeek': 2800,
        'specialOffers': [
          {
            'title': 'عرض ٣ أيام',
            'days': 3,
            'pricePerDay': 420,
            'label': 'عرض ٣ أيام',
          },
        ],
      },
      {
        'id': 'vac_hurghada_1',
        'title': 'شاليه الغردقة — قريب من الشاطئ',
        'price': '10,500',
        'dailyPrice': '520',
        'location': 'الجونة، الغردقة',
        'governorate': 'الغردقة',
        'region': 'الغردقة',
        'lat': 27.3942,
        'lng': 33.6782,
        'image': 'assets/images/home5.jpg',
        'beds': '3',
        'baths': '2',
        'area': '110',
        'ownerId': 'owner_redsea',
        'type': 'شاليهات',
        'amenities': [
          'قريب من البحر',
          'مكيف',
          'واي فاي',
          'مطبخ',
          'مناسب للعائلات',
          'سيارة متاحة',
        ],
        'furnished': true,
        'listingMode': 'rent',
        'status': 'approved',
        'isDemo': true,
        'shortStay': true,
        'phone': '01044443333',
        'supportedDurations': ['يوم', 'أسبوع', 'شهر'],
        'corporateEligible': false,
        'nearbyBeachMinutes': 6,
        'carAvailable': true,
        'familyFriendly': true,
        'independentHouse': true,
        'packageHalfWeek': 3100,
        'specialOffers': [
          {
            'title': 'نصف أسبوع',
            'days': 7,
            'pricePerDay': 443,
            'label': 'نصف أسبوع',
          },
        ],
      },
      {
        'id': 'vac_sharm_1',
        'title': 'فيلا شرم الشيخ للعائلات — نبق',
        'price': '14,000',
        'dailyPrice': '700',
        'location': 'نبق، شرم الشيخ',
        'governorate': 'شرم الشيخ',
        'region': 'شرم الشيخ',
        'lat': 28.0000,
        'lng': 34.4200,
        'image': 'assets/images/home4.jpg',
        'beds': '4',
        'baths': '3',
        'area': '180',
        'ownerId': 'owner_sharm',
        'type': 'فلل',
        'amenities': [
          'قريب من البحر',
          'بيت مستقل',
          'مناسب للعائلات',
          'مطبخ',
          'مكيف',
          'واي فاي',
          'تشطيب لوكس',
          'سراير متعددة',
        ],
        'furnished': true,
        'listingMode': 'rent',
        'status': 'approved',
        'isDemo': true,
        'isFeatured': true,
        'shortStay': true,
        'phone': '01022221111',
        'supportedDurations': ['يوم', 'أسبوع', 'شهر'],
        'corporateEligible': false,
        'nearbyBeachMinutes': 4,
        'carAvailable': true,
        'familyFriendly': true,
        'independentHouse': true,
        'packageHalfWeek': 4200,
        'specialOffers': [
          {
            'title': 'عرض ٣ أيام',
            'days': 3,
            'pricePerDay': 650,
            'label': 'عرض ٣ أيام',
          },
          {
            'title': 'نصف أسبوع',
            'days': 7,
            'pricePerDay': 600,
            'label': 'نصف أسبوع',
          },
        ],
      },
      // ===== Qalyubia =====
      {
        'id': 'egy12',
        'title': 'شقة للإيجار - بنها',
        'price': '5,500',
        'location': 'بنها، القليوبية',
        'governorate': 'القليوبية',
        'lat': 30.4660,
        'lng': 31.1849,
        'image': 'assets/images/home6.jpg',
        'beds': '2',
        'baths': '1',
        'area': '100',
        'ownerId': 'owner_12',
        'type': 'شقق',
        'amenities': ['هادئة', 'مفروشة جزئياً'],
        'furnished': false,
        'listingMode': 'rent',
        'status': 'approved',
        'isDemo': true,
        'phone': '01012345678',
        'supportedDurations': ['شهر', 'سنة'],
        'corporateEligible': true,
      },
      // ===== Sharqia =====
      {
        'id': 'egy13',
        'title': 'شقة للإيجار - الزقازيق',
        'price': '4,800',
        'location': 'الزقازيق، الشرقية',
        'governorate': 'الشرقية',
        'lat': 30.5877,
        'lng': 31.5020,
        'image': 'assets/images/home7.jpg',
        'beds': '2',
        'baths': '1',
        'area': '95',
        'ownerId': 'owner_13',
        'type': 'شقق',
        'amenities': ['قريبة من الجامعة', 'مكيفة'],
        'furnished': true,
        'listingMode': 'rent',
        'status': 'approved',
        'isDemo': true,
        'phone': '01012345678',
        'supportedDurations': ['شهر', 'سنة'],
        'corporateEligible': true,
      },
    ];
  }

  /// سكن مشترك تجريبي للمالك owner@ejari.app — 8 أسرّة، 4 غرف.
  static Map<String, dynamic> getSharedAccommodationProperty() {
    final now = DateTime.now();
    final bedUnits = List.generate(8, (i) {
      final roomIndex = i ~/ 2;
      final occupied = i < 5;
      return {
        'id': 'bed_${i + 1}',
        'roomId': 'room_${String.fromCharCode(97 + roomIndex)}',
        'label': 'سرير ${i + 1} — غرفة ${String.fromCharCode(65 + roomIndex)}',
        'status': occupied ? 'occupied' : 'vacant',
        if (occupied)
          'tenantEmail': 'tenant_${i + 1}@demo.ejari.app',
        if (occupied)
          'leaseStart': now.subtract(Duration(days: 15 + i * 3)).toIso8601String(),
        if (occupied)
          'leaseEnd': now.add(Duration(days: 30 + i * 5)).toIso8601String(),
        if (occupied) 'paymentStatus': i == 2 ? 'overdue' : 'paid',
      };
    });

    final roomUnits = List.generate(4, (i) {
      final roomBeds = bedUnits.where((b) => b['roomId'] == 'room_${String.fromCharCode(97 + i)}');
      final occupiedCount =
          roomBeds.where((b) => b['status'] == 'occupied').length;
      return {
        'id': 'room_${String.fromCharCode(97 + i)}',
        'label': 'غرفة ${String.fromCharCode(65 + i)}',
        'bedCount': 2,
        'occupiedBeds': occupiedCount,
        'status': occupiedCount == 2
            ? 'full'
            : occupiedCount == 0
                ? 'vacant'
                : 'partial',
      };
    });

    return {
      'id': 'shared_egy1',
      'title': 'سكن مشترك مفروش — المعادي (٨ أسرّة)',
      'price': '2,500',
      'location': 'المعادي، القاهرة',
      'governorate': 'القاهرة',
      'lat': 29.9600,
      'lng': 31.2700,
      'image': 'assets/images/properties/shared_bed.jpg',
      'beds': '8',
      'baths': '2',
      'area': '180',
      'ownerId': 'owner@ejari.app',
      'ownerEmail': 'owner@ejari.app',
      'type': 'سكن مشترك',
      'accommodationType': 'bed',
      'totalBeds': 8,
      'totalRooms': 4,
      'bedUnits': bedUnits,
      'roomUnits': roomUnits,
      'amenities': ['واي فاي', 'مطبخ مشترك', 'تكييف', 'أمن 24/7'],
      'furnished': true,
      'listingMode': 'rent',
      'status': 'approved',
      'isDemo': true,
      'isFeatured': true,
      'phone': '01012345678',
      'supportedDurations': ['يوم', 'أسبوع', 'شهر'],
      'corporateEligible': false,
      'dynamicPricing': {
        'daily': 150,
        'weekly': 800,
        'monthly': 2500,
        'seasonalRate': 2800,
        'seasonalLabel': 'سعر موسمي',
        'useManual': true,
      },
      'perBedPricing': {
        'daily': 150,
        'weekly': 800,
        'monthly': 2500,
      },
      'depositAmount': '500',
      'depositRate': 0.20,
    };
  }

  /// 23 مستأجر تجريبي لإدارة الإشغال.
  static List<Map<String, dynamic>> getSharedOccupancyTenants() {
    final now = DateTime.now();
    final names = [
      'أحمد محمود', 'سارة علي', 'محمد حسن', 'فاطمة إبراهيم', 'كريم يوسف',
      'نور الدين', 'ياسمين أحمد', 'عمر خالد', 'مريم سعيد', 'حسام فتحي',
      'دينا محمد', 'طارق عبد الله', 'رانيا محسن', 'وليد سالم', 'هبة ناصر',
      'إسلام رضوان', 'ليلى كمال', 'باسم عادل', 'شيماء فاروق', 'مصطفى جمال',
      'ريham توفيق', 'عبد الرحمن', 'سلma حسين',
    ];
    return List.generate(23, (i) {
      final isOverdue = i == 2 || i == 7 || i == 15;
      final isLivingWithoutPay = i == 15;
      final bedNum = (i % 8) + 1;
      return {
        'id': 'occ_tenant_$i',
        'name': names[i],
        'email': 'tenant_${(i % 8) + 1}@demo.ejari.app',
        'phone': '010${(10000000 + i).toString().substring(1)}',
        'propertyId': 'shared_egy1',
        'bedId': 'bed_$bedNum',
        'bedLabel': 'سرير $bedNum',
        'leaseStart': now.subtract(Duration(days: 10 + i)).toIso8601String(),
        'leaseEnd': now.add(Duration(days: 20 + i * 2)).toIso8601String(),
        'paymentStatus': isLivingWithoutPay
            ? 'living_without_pay'
            : isOverdue
                ? 'overdue'
                : 'paid',
        'preEntryPaid': i != 4,
        'monthlyRent': 2500,
        'lastPaymentDate': isOverdue
            ? now.subtract(const Duration(days: 35)).toIso8601String()
            : now.subtract(Duration(days: i % 20)).toIso8601String(),
      };
    });
  }
}
