class MockDataSeeder {
  static List<Map<String, dynamic>> getEgyptianProperties() {
    return [
      // ===== Cairo =====
      {
        'id': 'egy1',
        'title': 'شقة فاخرة على النيل - المعادي',
        'price': '15,000',
        'location': 'المعادي، القاهرة',
        'governorate': 'القاهرة',
        'lat': 29.9537,
        'lng': 31.2559,
        'image': 'assets/images/home1.jpg',
        'beds': '3',
        'baths': '2',
        'area': '200',
        'ownerId': 'owner@ejari.app',
        'type': 'شقق',
        'amenities': ['إطلالة نيلية', 'أمن 24/7', 'تكييف مركزي', 'موقف سيارات'],
        'furnished': true,
        'listingMode': 'rent',
        'status': 'approved',
        'isDemo': true,
        'phone': '01012345678',
        'supportedDurations': ['يوم', 'أسبوع', 'شهر', 'سنة'],
        'corporateEligible': true,
      },
      {
        'id': 'egy2',
        'title': 'فيلا مستقلة التجمع الخامس',
        'price': '45,000',
        'location': 'التجمع الخامس، القاهرة',
        'governorate': 'القاهرة',
        'lat': 30.0166,
        'lng': 31.4398,
        'image': 'assets/images/home2.jpg',
        'beds': '5',
        'baths': '4',
        'area': '450',
        'ownerId': 'owner@ejari.app',
        'type': 'فلل',
        'amenities': ['حمام سباحة', 'حديقة خاصة', 'تشطيب ألترا مودرن'],
        'furnished': true,
        'listingMode': 'rent',
        'status': 'approved',
        'isDemo': true,
        'phone': '01012345678',
        'supportedDurations': ['شهر', 'سنة'],
        'corporateEligible': true,
      },
      {
        'id': 'egy3',
        'title': 'استوديو مفروش - مدينة نصر',
        'price': '6,000',
        'location': 'مدينة نصر، القاهرة',
        'governorate': 'القاهرة',
        'lat': 30.0541,
        'lng': 31.3283,
        'image': 'assets/images/home7.jpg',
        'beds': '1',
        'baths': '1',
        'area': '65',
        'ownerId': 'owner_3',
        'type': 'استوديو',
        'amenities': ['مفروش بالكامل', 'واي فاي', 'بالقرب من سيتي ستارز'],
        'furnished': true,
        'listingMode': 'rent',
        'status': 'approved',
        'isDemo': true,
        'phone': '01012345678',
        'supportedDurations': ['يوم', 'أسبوع', 'شهر'],
        'corporateEligible': true,
      },
      {
        'id': 'egy8',
        'title': 'شقة للإيجار - مصر الجديدة',
        'price': '12,000',
        'location': 'مصر الجديدة، القاهرة',
        'governorate': 'القاهرة',
        'lat': 30.0872,
        'lng': 31.3308,
        'image': 'assets/images/home1.jpg',
        'beds': '2',
        'baths': '1',
        'area': '120',
        'ownerId': 'owner_8',
        'type': 'شقق',
        'amenities': ['مفروشة', 'أسانسير', 'قريبة من المترو'],
        'furnished': true,
        'listingMode': 'rent',
        'status': 'approved',
        'isDemo': true,
        'phone': '01012345678',
        'supportedDurations': ['شهر', 'سنة'],
        'corporateEligible': true,
      },
      {
        'id': 'egy9',
        'title': 'شقة يومية - وسط البلد',
        'price': '800',
        'location': 'وسط البلد، القاهرة',
        'governorate': 'القاهرة',
        'lat': 30.0444,
        'lng': 31.2357,
        'image': 'assets/images/home3.jpg',
        'beds': '1',
        'baths': '1',
        'area': '55',
        'ownerId': 'owner_9',
        'type': 'شقق',
        'amenities': ['إيجار يومي', 'مفروش', 'واي فاي'],
        'furnished': true,
        'listingMode': 'rent',
        'status': 'approved',
        'isDemo': true,
        'phone': '01012345678',
        'supportedDurations': ['يوم', 'أسبوع'],
        'corporateEligible': false,
      },
      // ===== Giza =====
      {
        'id': 'egy4',
        'title': 'شقة دوبلكس - الشيخ زايد',
        'price': '22,000',
        'location': 'الشيخ زايد، الجيزة',
        'governorate': 'الجيزة',
        'lat': 30.0345,
        'lng': 30.9850,
        'image': 'assets/images/home3.jpg',
        'beds': '4',
        'baths': '3',
        'area': '320',
        'ownerId': 'owner_4',
        'type': 'دوبلكس',
        'amenities': ['روف خاص', 'كمبوند مغلق', 'كلوب هاوس'],
        'furnished': false,
        'listingMode': 'rent',
        'status': 'approved',
        'isDemo': true,
        'phone': '01012345678',
        'supportedDurations': ['شهر', 'سنة'],
        'corporateEligible': true,
      },
      {
        'id': 'egy5',
        'title': 'شقة لقطة للبيع - المهندسين',
        'price': '3,500,000',
        'location': 'المهندسين، الجيزة',
        'governorate': 'الجيزة',
        'lat': 30.0520,
        'lng': 31.2017,
        'image': 'assets/images/home4.jpg',
        'beds': '3',
        'baths': '2',
        'area': '180',
        'ownerId': 'owner_5',
        'type': 'شقق',
        'amenities': ['مسجل شهر عقاري', 'موقع تجاري'],
        'furnished': false,
        'listingMode': 'for_sale',
        'status': 'approved',
        'isDemo': true,
        'phone': '01012345678',
        'supportedDurations': [],
        'corporateEligible': false,
      },
      {
        'id': 'egy10',
        'title': 'شقة للإيجار - ٦ أكتوبر',
        'price': '9,500',
        'location': '٦ أكتوبر، الجيزة',
        'governorate': 'الجيزة',
        'lat': 29.9285,
        'lng': 30.9188,
        'image': 'assets/images/home4.jpg',
        'beds': '2',
        'baths': '2',
        'area': '140',
        'ownerId': 'owner_10',
        'type': 'شقق',
        'amenities': ['كمبوند', 'موقف', 'أمن'],
        'furnished': true,
        'listingMode': 'rent',
        'status': 'approved',
        'isDemo': true,
        'phone': '01012345678',
        'supportedDurations': ['شهر', 'سنة'],
        'corporateEligible': true,
      },
      // ===== Alexandria =====
      {
        'id': 'egy6',
        'title': 'شقة بانوراما بحر - جليم',
        'price': '12,000',
        'location': 'جليم، الإسكندرية',
        'governorate': 'الإسكندرية',
        'lat': 31.2407,
        'lng': 29.9701,
        'image': 'assets/images/home5.jpg',
        'beds': '2',
        'baths': '2',
        'area': '150',
        'ownerId': 'owner_6',
        'type': 'شقق',
        'amenities': ['إطلالة مباشرة على البحر', 'مكيفة', 'أسانسير'],
        'furnished': true,
        'listingMode': 'rent',
        'status': 'approved',
        'isDemo': true,
        'phone': '01012345678',
        'supportedDurations': ['أسبوع', 'شهر', 'سنة'],
        'corporateEligible': true,
      },
      {
        'id': 'egy11',
        'title': 'شقة للإيجار - سموحة',
        'price': '10,500',
        'location': 'سموحة، الإسكندرية',
        'governorate': 'الإسكندرية',
        'lat': 31.2156,
        'lng': 29.9553,
        'image': 'assets/images/home5.jpg',
        'beds': '3',
        'baths': '2',
        'area': '165',
        'ownerId': 'owner_11',
        'type': 'شقق',
        'amenities': ['مفروشة', 'بالقرب من الكورنيش'],
        'furnished': true,
        'listingMode': 'rent',
        'status': 'approved',
        'isDemo': true,
        'phone': '01012345678',
        'supportedDurations': ['شهر', 'سنة'],
        'corporateEligible': true,
      },
      // ===== North Coast =====
      {
        'id': 'egy7',
        'title': 'شاليه الساحل الشمالي',
        'price': '2,500',
        'location': 'سيدي عبدالرحمن، الساحل الشمالي',
        'governorate': 'مطروح',
        'lat': 30.9320,
        'lng': 28.7180,
        'image': 'assets/images/home6.jpg',
        'beds': '3',
        'baths': '2',
        'area': '120',
        'ownerId': 'owner_7',
        'type': 'شاليهات',
        'amenities': ['قرية سياحية', 'أكوا بارك', 'مكيف'],
        'furnished': true,
        'listingMode': 'rent',
        'status': 'approved',
        'isDemo': true,
        'phone': '01012345678',
        'supportedDurations': ['يوم', 'أسبوع'],
        'corporateEligible': false,
      },
      // ===== Qalyubia =====
      {
        'id': 'egy12',
        'title': 'شقة للإيجار - بنها',
        'price': '5,500',
        'location': 'بنها، القليوبية',
        'governorate': 'القليوبية',
        'lat': 30.4660,
        'lng': 31.1849,
        'image': 'assets/images/home6.jpg',
        'beds': '2',
        'baths': '1',
        'area': '100',
        'ownerId': 'owner_12',
        'type': 'شقق',
        'amenities': ['هادئة', 'مفروشة جزئياً'],
        'furnished': false,
        'listingMode': 'rent',
        'status': 'approved',
        'isDemo': true,
        'phone': '01012345678',
        'supportedDurations': ['شهر', 'سنة'],
        'corporateEligible': true,
      },
      // ===== Sharqia =====
      {
        'id': 'egy13',
        'title': 'شقة للإيجار - الزقازيق',
        'price': '4,800',
        'location': 'الزقازيق، الشرقية',
        'governorate': 'الشرقية',
        'lat': 30.5877,
        'lng': 31.5020,
        'image': 'assets/images/home7.jpg',
        'beds': '2',
        'baths': '1',
        'area': '95',
        'ownerId': 'owner_13',
        'type': 'شقق',
        'amenities': ['قريبة من الجامعة', 'مكيفة'],
        'furnished': true,
        'listingMode': 'rent',
        'status': 'approved',
        'isDemo': true,
        'phone': '01012345678',
        'supportedDurations': ['شهر', 'سنة'],
        'corporateEligible': true,
      },
    ];
  }
}
