// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // Project IDs must match android/app/google-services.json + iOS plist.
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxVVVTRFiPaLvTkXFCh-rYVPSC4ImagbY',
    appId: '1:1041631611064:web:757c9f9bc4cfc959ab4c4d',
    messagingSenderId: '1041631611064',
    projectId: 'ejari-elite-1',
    authDomain: 'ejari-elite-1.firebaseapp.com',
    storageBucket: 'ejari-elite-1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDus2ib_4CL4nvPmlUY2vFFrBP9gBS6j4',
    appId: '1:1041631611064:android:2d10902716ce6ccfab4c4d',
    messagingSenderId: '1041631611064',
    projectId: 'ejari-elite-1',
    storageBucket: 'ejari-elite-1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpCIVsfA37PSXwOCaz1aLtd5mXx347T6c',
    appId: '1:1041631611064:ios:fdfee2c4e527a654ab4c4d',
    messagingSenderId: '1041631611064',
    projectId: 'ejari-elite-1',
    storageBucket: 'ejari-elite-1.firebasestorage.app',
    iosBundleId: 'com.ejari.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBpCIVsfA37PSXwOCaz1aLtd5mXx347T6c',
    appId: '1:1041631611064:ios:f2c8ce9dc6c6869bab4c4d',
    messagingSenderId: '1041631611064',
    projectId: 'ejari-elite-1',
    storageBucket: 'ejari-elite-1.firebasestorage.app',
    iosBundleId: 'com.example.ejariMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBxVVVTRFiPaLvTkXFCh-rYVPSC4ImagbY',
    appId: '1:1041631611064:web:3180c6250c8a17bbab4c4d',
    messagingSenderId: '1041631611064',
    projectId: 'ejari-elite-1',
    authDomain: 'ejari-elite-1.firebaseapp.com',
    storageBucket: 'ejari-elite-1.firebasestorage.app',
  );
}
