// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlSUWsnkPU2x6_16Gu8-2u29xN9x03Blo',
    appId: '1:349888023290:web:dfd919ca651687bf541743',
    messagingSenderId: '349888023290',
    projectId: 'ejari-mobile-d9f8e',
    authDomain: 'ejari-mobile-d9f8e.firebaseapp.com',
    storageBucket: 'ejari-mobile-d9f8e.firebasestorage.app',
    measurementId: 'G-ZV234WN4YX',
  );

  // Project IDs must match android/app/google-services.json + iOS plist.

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAx7ay3v8mv1f5vFvDeavp3VUU4CE36RyE',
    appId: '1:349888023290:android:1abe87d3a6207194541743',
    messagingSenderId: '349888023290',
    projectId: 'ejari-mobile-d9f8e',
    storageBucket: 'ejari-mobile-d9f8e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCC7ZKZERElgRWkKpbfpMoJqErPhYU0V-A',
    appId: '1:349888023290:ios:0f2cea65fe5c801a541743',
    messagingSenderId: '349888023290',
    projectId: 'ejari-mobile-d9f8e',
    storageBucket: 'ejari-mobile-d9f8e.firebasestorage.app',
    iosBundleId: 'com.ejari.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCC7ZKZERElgRWkKpbfpMoJqErPhYU0V-A',
    appId: '1:349888023290:ios:dfbde025d3425283541743',
    messagingSenderId: '349888023290',
    projectId: 'ejari-mobile-d9f8e',
    storageBucket: 'ejari-mobile-d9f8e.firebasestorage.app',
    iosBundleId: 'com.example.ejariMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBlSUWsnkPU2x6_16Gu8-2u29xN9x03Blo',
    appId: '1:349888023290:web:d6e0f02a0faf335d541743',
    messagingSenderId: '349888023290',
    projectId: 'ejari-mobile-d9f8e',
    authDomain: 'ejari-mobile-d9f8e.firebaseapp.com',
    storageBucket: 'ejari-mobile-d9f8e.firebasestorage.app',
    measurementId: 'G-4C3B71P52D',
  );

}